### ISSUE TITLE
Update the README or samples with instructions for Elixir.

### ISSUE THREAD

**Issue by idyll** [travelping/eradius#142] opened 2018-04-10 16:12 UTC
I have been trying to use the Elixir sample but it doesn't seem to stay running. I can only seem to get it working inside of spawn.

I've looked at https://github.com/xerions/exradius as well but again can only keep things running inside a spawn.

I'm sure there's just something dumb I am missing. But I have no idea what. I've done this:
```
  Instead of :application.ensure_all_started(:eradius)
  add :eradius to :applications

  Instead of spawn, simply add :eradius.modules_ready([__MODULE__]) to your Application
  start/2 callback.
```

and copied the config.

Any suggestions would be appreciated. I'm willing to help update the docs once I determine what's wrong.

**Comment by surik** [comment] 2018-04-10 16:15
Hi @idyll, do you have an example how you are trying to run it?

**Comment by surik** [comment] 2018-04-10 16:29
I would glad to help but this amount of information doesn't show me what could be wrong. Are you able to provide a minimal test case which I can reproduce on my local machine?

**Comment by idyll** [comment] 2018-04-10 16:31
Sure. Let me push something up to github.

**Comment by idyll** [comment] 2018-04-10 16:54
Okay I have pushed an example that I am working on here.
   https://github.com/idyll/radius-example

I pulled in a couple of files from https://github.com/xerions/exradius to get it going quickly.

**Comment by surik** [comment] 2018-04-10 17:39
Ah I see your problem. You need do `:eradius.modules_ready([RadiusServer])` in `RadiusExample.Application.start/2` since you have radius handler implementation in that module. Then it works:

```
$ iex -S mix
Erlang/OTP 20 [erts-9.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
...
19:37:18.776 [info] Starting RADIUS Listener at 0.0.0.0:1812
19:37:18.791 [info] Application eradius started on node nonode@nohost
19:37:18.832 [info] Application radius_example started on node nonode@nohost
Interactive Elixir (1.6.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> RadiusServer.client
[info] Authenticated user foo with password test^@^@^@^@^@^@^@^@^@^@^@^@
19:37:23.413 [info] 0.0.0.0:64611 [0]: Access-Request
19:37:23.413 [info] 0.0.0.0:64611 [0]: Access-Accept
{:radius_request, 0, :accept, [], "secret",
 <<20, 15, 172, 251, 70, 255, 186, 201, 134, 170, 11, 43, 133, 170, 17, 182>>,
 false, ""}
```

**Comment by idyll** [comment] 2018-04-10 17:49
Thanks!

I will clean up that repos and add a better readme. That way you only have to explain it to someone once ;)

**Comment by surik** [comment] 2018-04-10 17:57
There is a doc section for `eradius:modules_ready` which explains that modules should implement `eradius_server` callbacks. But I got your point, maybe it makes sense to separate application module and radius handler itself in the sample application. 

Thank you for feedback.

**Comment by idyll** [comment] 2018-04-10 18:02
No, thank you. It makes so much more sense now. :)

**Comment by vkatsuba** [comment] 2020-11-12 19:47
Closing now as we now have docs in `README.md`, please feel free to re-open if you will have any issues in further.

**Closed by vkatsuba** 2020-11-12 19:47 UTC
Labels: discussion
